import logging
import shutil
from pathlib import Path
from importlib.resources import files, as_file

from precice_config_graph import nodes as n

import precicecasegenerate.helper as helper

logger = logging.getLogger(__name__)


class UtilityFileCreator:
    """
    A class to create utility files for the generated project.
    """

    def __init__(self, participant_solver_map: dict[n.ParticipantNode, str]):
        """
        Initialize a UtilityFileCreator object, which creates a global clean.sh file, a global README.md file
        and a run.sh file for each participant-solver pair.
        :param participant_solver_map: A dict mapping participants to their solver names.
        """
        self.participant_solver_map = participant_solver_map

    def create_utility_files(self, parent_directory: Path = "./") -> None:
        """
        Create all utility files for the generated project:
        clean.sh, README.md and run.sh for each participant-solver pair.
        :param parent_directory: The directory from which to save the files.
        :return: None
        """
        # Convert to Path object just in case
        parent_directory = Path(parent_directory)
        self._create_clean_file(parent_directory)
        # Create a run file for each participant
        for participant in self.participant_solver_map:
            participant_directory = helper.get_participant_solver_directory(parent_directory, participant.name,
                                                                            self.participant_solver_map[participant])
            self._create_run_file(participant_directory)
        self._create_readme_file(parent_directory)

    def _create_clean_file(self, directory: Path = "./") -> None:
        """
        Create a clean-file for the simulation in the given directory.
        This copies the template file `precicecasegenerate/templates/clean.sh` to the specified directory.
        :param directory: The directory to save the file in.
        :return: None
        """
        # Convert to Path object just in case
        directory = Path(directory)
        # Get the file to copy
        src = files("precicecasegenerate.templates") / "clean.sh"
        # Create directory if it does not exist
        directory.mkdir(parents=True, exist_ok=True)

        file_path: Path = directory / src.name

        # Use as_file to get a real path even if the file is zipped
        with as_file(src) as real_src_path:
            shutil.copy2(real_src_path, file_path)
        logger.debug(f"File clean.sh written to {file_path.resolve()}")

    def _create_run_file(self, directory: Path = "./") -> None:
        """
        Create a run file for a participant in the given directory.
        This copies the template file `precicecasegenerate/templates/run.sh` to the specified directory.
        :param directory: The directory to save the file in.
        :return: None
        """
        # Convert to Path object just in case
        directory = Path(directory)
        # Get the file to copy
        src = files("precicecasegenerate.templates") / "run.sh"
        # Create directory if it does not exist
        directory.mkdir(parents=True, exist_ok=True)

        file_path: Path = directory / src.name

        # Use as_file to get a real path
        with as_file(src) as real_src_path:
            shutil.copy2(real_src_path, file_path)
        logger.debug(f"File run.sh written to {file_path.resolve()}")

    def _create_readme_file(self, directory: Path = "./", filename: str = "README.md") -> None:
        """
        Create a README file in the given directory.
        :param directory: The directory to save the file in.
        :return: None
        """
        # Convert to Path object just in case
        directory = Path(directory)
        # Create directory if it does not exist
        directory.mkdir(parents=True, exist_ok=True)

        file_path: Path = directory / filename
        with open(file_path, "w") as f:
            f.write(self._create_readme_str())
        logger.info(f"README file written to {file_path.resolve()}")

    def _create_readme_str(self) -> str:
        """
        Create a string representing the README file.
        return: A string representing the README file.
        """
        # Creates a vertical line between topics
        topic_separator: str = "\n---\n\n"

        readme_str: str = (
            "# Multiphysics Simulation Project\n"
            "\n"
            "> [!NOTE] This `README.md` file was auto-generated by preCICE case-generate.\n"
            "\n"
        )
        readme_str += topic_separator

        readme_str += (
            "## Project Overview\n"
            "\n"
            "This project uses **preCICE** for a multiphysics simulation involving:\n"
            "\n"
        )
        for participant in self.participant_solver_map:
            solver: str = self.participant_solver_map[participant]
            readme_str += (
                f"- Solver `{solver}` with participant `{participant.name}`\n"
            )
        readme_str += "\n"
        readme_str += (
            "### Project Structure\n"
            "\n"
            "Global files that are generated are: `precice-config.xml`, `README.md` and `clean.sh`. "
            "Additionally, for each participant, a folder with an `adapter-config.json` and a `run.sh` file are created.\n"
            "The folder structure is as follows:\n"
            "\n"
            "```\n"
            "_generated/\n"
            " ├── README.md\t\t\t# This file\n"
            " ├── clean.sh\t\t\t# Clean up script\n"
        )
        for participant in self.participant_solver_map:
            readme_str += (
                f" ├──{participant.name.lower()}-{self.participant_solver_map[participant].lower()}/\n"
                " │   ├── adapter-config.json\n"
                " │   └── run.sh\t\t\t# Not yet implemented\n"
            )
        readme_str += (
            " └── precice-config.xml\t\t# Global precice-config.xml file\n"
            "```\n"
            "\n"
            "\n"
        )
        # Explanation of precice-config.xml
        readme_str += (
            "- `precice-config.xml` is the global preCICE configuration file which defines the parameters "
            "and communication of participants\n"
        )
        # Explanation of adapter-config.json
        readme_str += (
            "- `adapter-config.json` is a configuration file to couple the solvers with preCICE.\n"
        )
        # Explanation of run.sh
        readme_str += (
            "- `run.sh` is a script that is meant to execute a participant. Note, however, that since "
            "different solvers are executed differently, this file is not implemented yet.\n"
        )
        # Explanation of clean.sh
        readme_str += (
            "- `clean.sh` removes any files in the current root directory that were not created by preCICE case-generate "
            "(and moves them to a backup folder).\n"
            "Execution:\n"
            "\n"
            "```bash\n"
            "./clean.sh [--force] [--dry-run]\n"
            "```\n"
            "\n"
            "- `--force` Deletes the files and any backup folders\n"
            "- `--dry-run` Does not delete any files, but prints files that would be deleted\n")

        readme_str += topic_separator

        readme_str += (
            "## Prerequisites\n"
            "\n"
            "Before running the simulation, ensure you have the following installed:\n"
            "\n"
            "- The preCICE coupling library\n"
        )
        for participant in self.participant_solver_map:
            solver: str = self.participant_solver_map[participant]
            readme_str += (
                f"- Solver `{solver}` and its dependencies\n"
            )

        readme_str += topic_separator

        readme_str += (
            "## Running the Simulation\n"
            "\n"
            "### Quick Start\n"
            "\n"
            "```bash\n"
            "# Navigate to the `_generated` folder\n"
            "cd _generated/\n"
            "\n"
            "# Implement the run script\n"
            "\n"
            "# Make the run script executable \n"
            "chmod +x run.sh\n"
            "\n"
            "# Execute the simulation\n"
            "./run.sh\n"
            "```\n"
        )

        readme_str += topic_separator

        readme_str += (
            "For more information, see the [preCICE documentation](https://precice.org/docs.html) and "
            "[precice-case-generate](https://github.com/precice/case-generate)."
        )
        return readme_str
